# : Manager [[[

[mgr]
cwd = { fg = "#c0c5c0" }

# Tab
tab_active = { fg = "#002216", bg = "#59ad8b", bold = true }
tab_inactive = { fg = "#005d43", bg = "#a5fbd5" }
tab_width = 1

# Find
find_keyword = { fg = "#ff7063", bold = true, italic = true, underline = true }
find_position = { fg = "#ff7063", bold = true, italic = true }

# Marker
marker_copied = { fg = "#bc6767", bg = "#bc6767" }
marker_cut = { fg = "#833a3a", bg = "#833a3a" }
marker_marked = { fg = "#ff7063", bg = "#ff7063" }
marker_selected = { fg = "#df8482", bg = "#df8482" }

# Count
count_copied = { fg = "#ffe3e1", bg = "#833a3a" }
count_cut = { fg = "#ffe3e1", bg = "#833a3a" }
count_selected = { fg = "#002216", bg = "#df8482" }

# Border
border_symbol = " "
border_style  = { fg = "#83d7b3" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#002216", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#59ad8b", fg = "#002216", bold = true }
normal_alt  = { bg = "#3f4943", fg = "#95a099" }

# Select mode
select_main = { bg = "#84a494", fg = "#001d12", bold = true }
select_alt  = { bg = "#3f4943", fg = "#95a099" }

# Unset mode
unset_main = { bg = "#df8482", fg = "#380307", bold = true }
unset_alt  = { bg = "#3f4943", fg = "#95a099" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#59ad8b", bg = "#363a37" }
progress_error = { fg = "#ff7063", bg = "#363a37" }

# Permissions
permissions_t = { fg = "#3d5248" }
permissions_w = { fg = "#9f2b29" }
permissions_x = { fg = "#c91100" }
permissions_r = { fg = "#cb8b8b" }
permissions_s = { fg = "#00f6b1" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#59ad8b" }
active = { fg = "#df8482", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#59ad8b" }
value = { fg = "#c0c5c0" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#59ad8b", bold = true, bg = "#101412" }
inactive = { fg = "#84a494", bg = "#101412" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#59ad8b", bg = "#002216" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#59ad8b" }
title = {}
hovered = { fg = "#833a3a", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#363a37" }
cand = { fg = "#59ad8b" }
rest = { fg = "#002216" }
desc = { fg = "#c0c5c0" }
separator = " ▶ "
separator_style = { fg = "#c0c5c0" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#c0c5c0" }
run = { fg = "#c0c5c0" }
footer = { fg = "#001d12", bg = "#84a494" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#df8482" }
title_warn = { fg = "#59ad8b" }
title_error = { fg = "#ff7063" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#7b0007" },
    { name = "*", is = "exec", fg = "#ffb1a8" },

    # Fallback
    { name = "*", fg = "#c0c5c0" },
    { name = "*/", fg = "#83d7b3" },
]

# : ]]]
