# : Manager [[[

[mgr]
cwd = { fg = "#c1c4c0" }

# Tab
tab_active = { fg = "#002212", bg = "#66ab83", bold = true }
tab_inactive = { fg = "#105d3b", bg = "#b1f9cc" }
tab_width = 1

# Find
find_keyword = { fg = "#ff7063", bold = true, italic = true, underline = true }
find_position = { fg = "#ff7063", bold = true, italic = true }

# Marker
marker_copied = { fg = "#b96973", bg = "#b96973" }
marker_cut = { fg = "#803c44", bg = "#803c44" }
marker_marked = { fg = "#ff7063", bg = "#ff7063" }
marker_selected = { fg = "#da858d", bg = "#da858d" }

# Count
count_copied = { fg = "#ffe3e4", bg = "#803c44" }
count_cut = { fg = "#ffe3e4", bg = "#803c44" }
count_selected = { fg = "#002212", bg = "#da858d" }

# Border
border_symbol = " "
border_style  = { fg = "#8fd6ab" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#002212", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#66ab83", fg = "#002212", bold = true }
normal_alt  = { bg = "#404942", fg = "#96a097" }

# Select mode
select_main = { bg = "#88a490", fg = "#041c10", bold = true }
select_alt  = { bg = "#404942", fg = "#96a097" }

# Unset mode
unset_main = { bg = "#da858d", fg = "#37030e", bold = true }
unset_alt  = { bg = "#404942", fg = "#96a097" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#66ab83", bg = "#363a37" }
progress_error = { fg = "#ff7063", bg = "#363a37" }

# Permissions
permissions_t = { fg = "#405345" }
permissions_w = { fg = "#982e38" }
permissions_x = { fg = "#c91100" }
permissions_r = { fg = "#c98c93" }
permissions_s = { fg = "#2bdb8d" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#66ab83" }
active = { fg = "#da858d", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#66ab83" }
value = { fg = "#c1c4c0" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#66ab83", bold = true, bg = "#101411" }
inactive = { fg = "#88a490", bg = "#101411" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#66ab83", bg = "#002212" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#66ab83" }
title = {}
hovered = { fg = "#803c44", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#363a37" }
cand = { fg = "#66ab83" }
rest = { fg = "#002212" }
desc = { fg = "#c1c4c0" }
separator = " ▶ "
separator_style = { fg = "#c1c4c0" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#c1c4c0" }
run = { fg = "#c1c4c0" }
footer = { fg = "#041c10", bg = "#88a490" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#da858d" }
title_warn = { fg = "#66ab83" }
title_error = { fg = "#ff7063" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#7b0007" },
    { name = "*", is = "exec", fg = "#ffb1a8" },

    # Fallback
    { name = "*", fg = "#c1c4c0" },
    { name = "*/", fg = "#8fd6ab" },
]

# : ]]]
